#!/bin/sh
/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S rtl8370_asicdrv.c -o rtl8370_asicdrv.S

/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os  -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S rtk_api.c -o rtk_api.S

/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os  -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S smi.c -o smi.S

/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os  -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S rtl8370_asicdrv_vlan.c -o rtl8370_asicdrv_vlan.S

/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os  -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S rtl8370_asicdrv_dot1x.c -o rtl8370_asicdrv_dot1x.S

/home/RT6856/tools/buildroot-gcc342/bin/mipsel-linux-gcc -Wa,-gstabs -D__ASSEMBLY__ -gdwarf-2 -DDEBUG -Os  -D__KERNEL__ -DTEXT_BASE=0xBFC00000 -I/home/RT6856/boot-source/GPL_4000/include -fno-builtin -ffreestanding -nostdinc -isystem /home/RT6856/tools/buildroot-gcc342/bin/../lib/gcc/mipsel-linux-uclibc/3.4.2/include -pipe -DCONFIG_MIPS -D__MIPS__ -march=4kc -mtune=4kc -mabicalls -DRALINK_MDIO_ACCESS_FUN -DRALINK_SPI_UPGRADE_CHECK -DRALINK_RW_RF_REG_FUN -DP5_MAC_TO_NONE_MODE -DASIC_BOARD -DRT63365_ASIC_BOARD -DRT6855A_ASIC_BOARD -DRT63365_MP -DMAC_TO_REALTEK_MODE -I/home/RT6856/boot-source/GPL_4000/include/realtek -DAPPEND_CONFIG_FOLLOW -DUBOOT_ROM -DON_BOARD_DDR2 -DON_BOARD_DDR_WIDTH_16 -DON_BOARD_16BIT_DRAM_BUS -DON_BOARD_512M_DRAM_COMPONENT -DCFG_ENV_IS_IN_SPI -D_LITTLE_ENDIAN -DREALTEK_SW_R_VB -c -S rtl8370_asicdrv_led.c -o rtl8370_asicdrv_led.S

mv *.S GPL_4000/drivers/realtek/
